name: pciSeq
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - pip:
      - -r requirements.txt

#name: pciSeq
#channels:
#  - conda-forge
#dependencies:
#  - pip
#  - python=3.8
#  - numpy_groupies
#  - pandas
#  - dask
#  - scipy
#  - scikit-image
#  - scikit-learn
#  - tqdm
#  - numexpr
#  - flask
#  - natsort
#  - streamlit
#  - altair
#  - tomlkit
#  - pip:
#      - jupyterlab
#      - diplib
#      - pyvips
#      - redis
#      - fastremap
#      - pytest
#      - matplotlib
#      - laspy