name: pciSeq
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - opencv
  - numpy_groupies
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - tqdm
  - numexpr
  - flask
  - natsort
  - streamlit
  - altair
  - pip:
      - jupyterlab
      - diplib
      - pyvips
      - redis