

function classColorsCodes()
{
    var out = [

        {className: 'ENT9', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'ENT8', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'ENT6', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'ENT5', IdentifiedType: ' Backprojection', color: '#3DCCFF'},
        {className: 'ENT4', IdentifiedType: ' Basket', color: '#7757FA'},
        {className: 'ENT7', IdentifiedType: ' Basket', color: '#7757FA'},
        {className: 'ENT3', IdentifiedType: ' Bistratified', color: '#5938DB'},
        {className: 'ENT2', IdentifiedType: ' Bistratified', color: '#5938DB'},
        {className: 'ENT1', IdentifiedType: ' Cck Calb1/Slc17a8*', color: '#FF0000'},
        {className: 'ENTG1', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'ENTG4', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'ENTG2', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'ENTG3', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'ENTG6', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'ENTG5', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'ENTG7', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'ENMFB', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'MOL3', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'MOL2', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'MFOL1', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'MOL1', IdentifiedType: ' Cck Vip Cxcl14+', color: '#996E00'},
        {className: 'MFOL2', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'NFOL1', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'NFOL2', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'COP2', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'COP1', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'HBSER2', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'HBSER1', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'HBSER3', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'HBSER4', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'HBSER5', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'TEGLU15', IdentifiedType: ' IS2', color: '#FAE52E'},
        {className: 'TEGLU16', IdentifiedType: ' IS2', color: '#FAE52E'},
        {className: 'TEGLU5', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'TEGLU4', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'TEGLU22', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'TEGLU23', IdentifiedType: ' Ivy', color: '#994D91'},
        {className: 'TEGLU24', IdentifiedType: ' MGE NGF', color: '#994D91'},
        {className: 'TEGLU17', IdentifiedType: ' NGF/I-S transition', color: '#FF00E6'},
        {className: 'TEGLU18', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU19', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU14', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU13', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU21', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU10', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU11', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU20', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU12', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU9', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU8', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU7', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEINH10', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEINH11', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEINH12', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEINH9', IdentifiedType: ' O/LM', color: '#008FCC'},
        {className: 'OBINH5', IdentifiedType: ' O/LM', color: '#008FCC'},
        {className: 'TEINH5', IdentifiedType: ' O/LM', color: '#008FCC'},
        {className: 'TEINH6', IdentifiedType: ' O-Bi', color: '#0070AD'},
        {className: 'TEINH7', IdentifiedType: ' O-Bi', color: '#0070AD'},
        {className: 'TEINH8', IdentifiedType: ' O-Bi', color: '#0070AD'},
        {className: 'TEINH4', IdentifiedType: ' PC', color: '#00FF00'},
        {className: 'TEINH20', IdentifiedType: ' PC', color: '#00FF00'},
        {className: 'TEINH13', IdentifiedType: ' PC', color: '#00FF00'},
        {className: 'TEINH14', IdentifiedType: ' PC Other1', color: '#73E500'},
        {className: 'TEINH16', IdentifiedType: ' PC Other2', color: '#73E500'},
        {className: 'TEINH15', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        {className: 'TEINH19', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        {className: 'TEINH21', IdentifiedType: ' Trilaminar', color: '#1F663B'},
        {className: 'HYPEP7', IdentifiedType: ' Unidentified', color: '#A6A6A6'},
        {className: 'HYPEP6', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'DEINH8', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'MBDOP1', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'MBDOP2', IdentifiedType: ' Backprojection', color: '#3DCCFF'},
        {className: 'MEGLU14', IdentifiedType: ' Basket', color: '#7757FA'},
        {className: 'MEGLU11', IdentifiedType: ' Basket', color: '#7757FA'},
        {className: 'MEGLU10', IdentifiedType: ' Bistratified', color: '#5938DB'},
        {className: 'MEGLU9', IdentifiedType: ' Bistratified', color: '#5938DB'},
        {className: 'MEGLU8', IdentifiedType: ' Cck Calb1/Slc17a8*', color: '#FF0000'},
        {className: 'MEGLU7', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'MEGLU6', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'DEGLU5', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'MEGLU2', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'MEGLU3', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'MEGLU1', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'MEGLU5', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'MEGLU4', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'DEGLU4', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'DEGLU3', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'OBNBL1', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'MBCHO1', IdentifiedType: ' Cck Vip Cxcl14+', color: '#996E00'},
        {className: 'HBGLU9', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'SCGLU1', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'HBGLU10', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'SCGLU10', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'HBGLU2', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'HBGLU3', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'HBNOR', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'HBGLU1', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'DEGLU2', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'DEGLU1', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'MSN1', IdentifiedType: ' IS2', color: '#FAE52E'},
        {className: 'MSN2', IdentifiedType: ' IS2', color: '#FAE52E'},
        {className: 'MSN3', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'MSN5', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'MSN4', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'MSN6', IdentifiedType: ' Ivy', color: '#994D91'},
        {className: 'OEC', IdentifiedType: ' MGE NGF', color: '#994D91'},
        {className: 'DETPH', IdentifiedType: ' NGF/I-S transition', color: '#FF00E6'},
        {className: 'RGDG', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'RGSZ', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'OPC', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'SZNBL', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'EPMB', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'HYPEN', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'OBDOP2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'OBINH2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'OBINH3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'OBINH1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'OBINH4', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'OBNBL2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU6', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'TEGLU1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'DGGRC2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'DGGRC1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'DGNBL1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'DGNBL2', IdentifiedType: ' O/LM', color: '#008FCC'},
        {className: 'OBNBL3', IdentifiedType: ' O/LM', color: '#008FCC'},
        {className: 'HYPEP3', IdentifiedType: ' O/LM', color: '#008FCC'},
        {className: 'HYPEP2', IdentifiedType: ' O-Bi', color: '#0070AD'},
        {className: 'HYPEP1', IdentifiedType: ' O-Bi', color: '#0070AD'},
        {className: 'CBNBL2', IdentifiedType: ' O-Bi', color: '#0070AD'},
        {className: 'CBGRC', IdentifiedType: ' PC', color: '#00FF00'},
        {className: 'CR', IdentifiedType: ' PC', color: '#00FF00'},
        {className: 'CBNBL1', IdentifiedType: ' PC', color: '#00FF00'},
        {className: 'SEPNBL', IdentifiedType: ' PC Other1', color: '#73E500'},
        {className: 'OBNBL5', IdentifiedType: ' PC Other2', color: '#73E500'},
        {className: 'OBNBL4', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        {className: 'DECHO2', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        {className: 'HYPEP5', IdentifiedType: ' Trilaminar', color: '#1F663B'},
        {className: 'DEINH7', IdentifiedType: ' Unidentified', color: '#A6A6A6'},
        {className: 'HYPEP4', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'HBGLU8', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'HBGLU6', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'HBGLU7', IdentifiedType: ' Backprojection', color: '#3DCCFF'},
        {className: 'HBGLU5', IdentifiedType: ' Basket', color: '#7757FA'},
        {className: 'HBGLU4', IdentifiedType: ' Basket', color: '#7757FA'},
        {className: 'HBCHO2', IdentifiedType: ' Bistratified', color: '#5938DB'},
        {className: 'HBCHO1', IdentifiedType: ' Bistratified', color: '#5938DB'},
        {className: 'HBCHO3', IdentifiedType: ' Cck Calb1/Slc17a8*', color: '#FF0000'},
        {className: 'HBADR', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'HBCHO4', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'TECHO', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'DECHO1', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'SCINH1', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'HBINH8', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'HBINH7', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'HBINH5', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'CBINH2', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'CBPC', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'CBINH1', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'MEINH1', IdentifiedType: ' Cck Vip Cxcl14+', color: '#996E00'},
        {className: 'TEINH17', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'TEINH18', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'DEINH2', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'DEINH1', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'DEINH6', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'MEINH13', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'MEINH8', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'MEINH14', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'DEINH4', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'DEINH5', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'TEINH2', IdentifiedType: ' IS2', color: '#FAE52E'},
        {className: 'TEINH1', IdentifiedType: ' IS2', color: '#FAE52E'},
        {className: 'HBINH4', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'HBINH3', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'HBINH1', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'SCINH11', IdentifiedType: ' Ivy', color: '#994D91'},
        {className: 'MEINH3', IdentifiedType: ' MGE NGF', color: '#994D91'},
        {className: 'MEINH4', IdentifiedType: ' NGF/I-S transition', color: '#FF00E6'},
        {className: 'DEINH3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'MEINH2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'MEINH7', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'MEINH5', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'MEINH12', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'MEINH11', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'MEINH9', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'MEINH10', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'MEINH6', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'HBINH6', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'HBINH2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'SCGLU8', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'SCGLU9', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'SCGLU7', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'SCGLU2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'SCGLU3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'SCGLU4', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'SCGLU6', IdentifiedType: ' O/LM', color: '#008FCC'},
        {className: 'SCGLU5', IdentifiedType: ' O/LM', color: '#008FCC'},
        {className: 'SCINH5', IdentifiedType: ' O/LM', color: '#008FCC'},
        {className: 'SCINH6', IdentifiedType: ' O-Bi', color: '#0070AD'},
        {className: 'SCINH7', IdentifiedType: ' O-Bi', color: '#0070AD'},
        {className: 'HBINH9', IdentifiedType: ' O-Bi', color: '#0070AD'},
        {className: 'SCINH2', IdentifiedType: ' PC', color: '#00FF00'},
        {className: 'SCINH4', IdentifiedType: ' PC', color: '#00FF00'},
        {className: 'SCINH3', IdentifiedType: ' PC', color: '#00FF00'},
        {className: 'SCINH10', IdentifiedType: ' PC Other1', color: '#73E500'},
        {className: 'SCINH9', IdentifiedType: ' PC Other2', color: '#73E500'},
        {className: 'SCINH8', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        {className: 'TEINH3', IdentifiedType: ' Radiatum retrohip', color: '#3D855A'},
        {className: 'OBDOP1', IdentifiedType: ' Trilaminar', color: '#1F663B'},
        {className: 'HYPEP8', IdentifiedType: ' Unidentified', color: '#A6A6A6'},
        {className: 'ABC', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'VLMC2', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'VLMC1', IdentifiedType: ' Axo-axonic', color: '#3A19BD'},
        {className: 'VSMCA', IdentifiedType: ' Backprojection', color: '#3DCCFF'},
        {className: 'PER3', IdentifiedType: ' Basket', color: '#7757FA'},
        {className: 'VECA', IdentifiedType: ' Basket', color: '#7757FA'},
        {className: 'PER2', IdentifiedType: ' Bistratified', color: '#5938DB'},
        {className: 'PER1', IdentifiedType: ' Bistratified', color: '#5938DB'},
        {className: 'VECV', IdentifiedType: ' Cck Calb1/Slc17a8*', color: '#FF0000'},
        {className: 'VECC', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'MGL1', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'MGL2', IdentifiedType: ' Cck Cxcl14-', color: '#FF0000'},
        {className: 'MGL3', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'PVM2', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'PVM1', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'SCHW', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'SATG2', IdentifiedType: ' Cck Cxcl14+', color: '#996E00'},
        {className: 'SATG1', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'ACBG', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'ACOB', IdentifiedType: ' Cck Vip Cxcl14-', color: '#FF0000'},
        {className: 'ACTE1', IdentifiedType: ' Cck Vip Cxcl14+', color: '#996E00'},
        {className: 'ACTE2', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'ACNT1', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'ACNT2', IdentifiedType: ' CGE NGF', color: '#FF00E6'},
        {className: 'ACMB', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'EPEN', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'EPSC', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'CHOR', IdentifiedType: ' Hippocamposeptal', color: '#1FADEB'},
        {className: 'SYNOR3', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'SYNOR2', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'SYNOR1', IdentifiedType: ' IS1', color: '#BDA800'},
        {className: 'SYNOR4', IdentifiedType: ' IS2', color: '#FAE52E'},
        {className: 'SYNOR5', IdentifiedType: ' IS2', color: '#FAE52E'},
        {className: 'SYCHO2', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'SYCHO1', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'PSPEP1', IdentifiedType: ' IS3', color: '#DBC70F'},
        {className: 'PSPEP3', IdentifiedType: ' Ivy', color: '#994D91'},
        {className: 'PSPEP2', IdentifiedType: ' MGE NGF', color: '#994D91'},
        {className: 'PSPEP4', IdentifiedType: ' NGF/I-S transition', color: '#FF00E6'},
        {className: 'PSPEP5', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSPEP6', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSPEP7', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSPEP8', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSNF2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSNF3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSNF1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSNP1', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSNP3', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSNP2', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSNP5', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSNP4', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'PSNP6', IdentifiedType: ' Non Neuron', color: '#FFFFFF'},
        {className: 'Zero', IdentifiedType: 'Zero', color: '#000000'},


        // I added this
        {className: 'Other', IdentifiedType: 'Other', colorGroup: 'Other', color: '#C0C0C0'},


    ];

    return out
}