import { defineConfig } from 'vitepress'
// the per-function list under "Functions" is generated by gen_api.py
import apiFunctions from './api-nav.json'

// Config for the pciSeq docs. We used to run this on Docusaurus but moved to
// VitePress. The site is served from a subpath on GitHub Pages, hence base.
export default defineConfig({
  title: 'pciSeq',
  description: 'Probabilistic cell typing by in situ sequencing',
  lang: 'en-US',

  // Project site at https://acycliq.github.io/pciSeq_3d/
  base: '/pciSeq_3d/',

  // dark by default, like the old site
  appearance: 'dark',

  // don't die on a bad link while the docs are still being written
  ignoreDeadLinks: true,

  // turn on the built-in math (MathJax under the hood). needs the
  // markdown-it-mathjax3 dev dependency to be installed.
  markdown: {
    math: true,
  },

  themeConfig: {
    nav: [
      { text: 'Docs', link: '/' },
      { text: 'How it works', link: '/how-it-works/overview' },
      { text: 'The model', link: '/the-model/overview' },
      { text: 'API', link: '/api/reference' },
    ],

    sidebar: [
      { text: 'Introduction', link: '/' },
      {
        text: 'How it works',
        link: '/how-it-works/overview',
        items: [
          { text: 'Overview', link: '/how-it-works/overview' },
          { text: 'Block 1: Misread density', link: '/how-it-works/misread-density' },
          { text: 'Block 2: Warping the reference', link: '/how-it-works/warping-the-reference' },
          { text: 'Block 3: Cell to cell type', link: '/how-it-works/cell-to-celltype' },
          { text: 'Block 4: Spots to cells', link: '/how-it-works/spots-to-cells' },
        ],
      },
      {
        text: 'The model',
        link: '/the-model/overview',
        items: [
          { text: 'Overview', link: '/the-model/overview' },
          { text: 'Misread density', link: '/the-model/misread-density' },
          {
            text: 'Scale factors',
            link: '/the-model/scale-factors',
            items: [
              { text: 'Cell scale theta', link: '/the-model/scale-theta' },
              { text: 'Cell-gene scale gamma', link: '/the-model/scale-gamma' },
              { text: 'Efficiency eta', link: '/the-model/scale-eta' },
            ],
          },
          { text: 'Cell-class assignment', link: '/the-model/cell-class' },
          { text: 'Spot assignment', link: '/the-model/spot-assignment' },
          { text: 'Gene-gene dependence', link: '/the-model/gene-gene' },
          { text: 'Errata', link: '/the-model/errata' },
          { text: 'Appendix: self-consistency', link: '/the-model/appendix-self-consistency' },
        ],
      },
      {
        text: 'API reference',
        link: '/api/reference',
        items: [
          {
            text: 'Functions',
            link: '/api/reference',
            collapsed: true,
            items: apiFunctions,
          },
          { text: 'Configuration (opts)', link: '/api/configuration' },
        ],
      },
    ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/acycliq/pciSeq_3d' },
    ],

    editLink: {
      pattern: 'https://github.com/acycliq/pciSeq_3d/edit/dev_3d/website/docs/:path',
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: 'Built with VitePress.',
      copyright: 'Copyright © 2026 acycliq',
    },

    search: {
      provider: 'local',
    },
  },
})