

function classColorsCodes()
{
    var out = [

        {className: 'Inh.L1.LAMP5.NDNF',            IdentifiedType: 'Axo-axonic',       color: '#3A19BD'},
        {className: 'Inh.L1.LAMP5.GGT8P',              IdentifiedType: 'Axo-axonic',       color: '#3A19BD'},
        {className: 'Inh.L1.4.LAMP5.DUSP4',            IdentifiedType: 'Axo-axonic',       color: '#3A19BD'},
        {className: 'Inh.L6.LAMP5.C1QL2',                     IdentifiedType: 'Backprojection',   color: '#3DCCFF'},
        {className: 'Inh.L1.6.LAMP5.CA13',             IdentifiedType: 'Basket',           color: '#7757FA'},
        {className: 'Inh.L5.6.LAMP5.SFTA3',              IdentifiedType: 'Basket',           color: '#7757FA'},
        {className: 'Inh.L1.2.PAX6.SCGN',           IdentifiedType: 'Bistratified',     color: '#5938DB'},
        {className: 'Inh.L6.LAMP5.ANKRD20A11P',               IdentifiedType: 'Bistratified',     color: '#5938DB'},
        {className: 'Inh.L1.PAX6.CA4',                    IdentifiedType: 'Cck Calb1/Slc17a8*', color: '#FF0000'},
        {className: 'Inh.L1.PAX6.GRIP2',                    IdentifiedType: 'Cck Cxcl14-',      color: '#FF0000'},
        {className: 'Inh.L1.6.VIP.RCN1',                 IdentifiedType: 'Cck Cxcl14-',      color: '#FF0000'},
        {className: 'Inh.L1.3.PAX6.NABP1',                   IdentifiedType: 'Cck Cxcl14-',      color: '#FF0000'},
        {className: 'Inh.L1.VIP.PRSS8',      IdentifiedType: 'Cck Cxcl14+',      color: '#996E00'},
        {className: 'Inh.L1.VIP.TNFAIP8L3',      IdentifiedType: 'Cck Cxcl14+',      color: '#996E00'},
        {className: 'Inh.L1.ADARB2.ADAM33',        IdentifiedType: 'Cck Cxcl14+',      color: '#996E00'},
        {className: 'Inh.L1.SST.CXCL14',   IdentifiedType: 'Cck Cxcl14+',      color: '#996E00'},
        {className: 'Inh.L1.ADARB2.DISP2',           IdentifiedType: 'Cck Cxcl14+',      color: '#996E00'},
        {className: 'Inh.L1.VIP.SOX11',             IdentifiedType: 'Cck Vip Cxcl14-',  color: '#FF0000'},
        {className: 'Inh.L1.5.VIP.KCNJ2',         IdentifiedType: 'Cck Vip Cxcl14-',  color: '#FF0000'},
        {className: 'Inh.L1.6.VIP.PENK',            IdentifiedType: 'Cck Vip Cxcl14-',  color: '#FF0000'},
        {className: 'Inh.L1.6.VIP.RGS16',               IdentifiedType: 'Cck Vip Cxcl14+',  color: '#996E00'},
        {className: 'Inh.L2.6.VIP.VIP',         IdentifiedType: 'CGE NGF',          color: '#FF00E6'},
        {className: 'Inh.L3.6.VIP.KCTD13',            IdentifiedType: 'CGE NGF',          color: '#FF00E6'},
        {className: 'Inh.L1.VIP.PCDH20',          IdentifiedType: 'CGE NGF',          color: '#FF00E6'},
        {className: 'Inh.L1.2.VIP.PPAPDC1A',                 IdentifiedType: 'Hippocamposeptal', color: '#1FADEB'},
        {className: 'Inh.L2.4.VIP.DSEL',               IdentifiedType: 'Hippocamposeptal', color: '#1FADEB'},
        {className: 'Inh.L2.5.VIP.TOX2',               IdentifiedType: 'Hippocamposeptal', color: '#1FADEB'},
        {className: 'Inh.L1.3.VIP.ZNF322P1',             IdentifiedType: 'Hippocamposeptal', color: '#1FADEB'},
        {className: 'Inh.L3.VIP.CBLN1',        IdentifiedType: 'IS1',              color: '#BDA800'},
        {className: 'Inh.L1.3.VIP.GGH',         IdentifiedType: 'IS1',              color: '#BDA800'},
        {className: 'Inh.L1.3.VIP.ACHE',           IdentifiedType: 'IS1',              color: '#BDA800'},
        {className: 'Inh.L1.2.VIP.RPL41P3',                IdentifiedType: 'IS2',              color: '#FAE52E'},
        {className: 'Inh.L1.3.VIP.SSTR1',                 IdentifiedType: 'IS2',              color: '#FAE52E'},
        {className: 'Inh.L1.3.VIP.CCDC184',               IdentifiedType: 'IS3',              color: '#DBC70F'},
        {className: 'Inh.L2.4.VIP.LGI2',             IdentifiedType: 'IS3',              color: '#DBC70F'},
        {className: 'Inh.L1.4.VIP.CHRNA2',               IdentifiedType: 'IS3',              color: '#DBC70F'},
        {className: 'Inh.L6.SST.NPY',          IdentifiedType: 'Ivy',              color: '#994D91'},
        {className: 'Inh.L5.6.SST.ISOC1',           IdentifiedType: 'MGE NGF',          color: '#994D91'},
        {className: 'Inh.L5.6.SST.KLHL14',                  IdentifiedType: 'NGF/I-S transition', color: '#FF00E6'},
        {className: 'Inh.L4.6.SST.MTHFD2P6',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L3.5.SST.MAFB',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L4.5.PVALB.TRIM67',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L5.6.SST.TH',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L6.LHX6.GLP1R',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L5.6.PVALB.FAM150B',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L2.4.SST.AHR',                         IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L1.2.PVALB.TAC1',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L1.3.PVALB.WFDC2',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L2.4.PVALB.C8orf4',                  IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L5.PVALB.CNTNAP3P2',                  IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L5.6.PVALB.STON2',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L3.4.PVALB.HOMER3',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L1.6.PVALB.SCUBE3',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Inh.L3.6.PVALB.MFI2',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Exc.L2.4.RORB.GRIK1',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Exc.L3.4.RORB.RPS3P6',                         IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Exc.L4.RORB.BHLHE22',        IdentifiedType: 'O/LM',             color: '#008FCC'},
        {className: 'Exc.L4.RORB.CCDC168',         IdentifiedType: 'O/LM',             color: '#008FCC'},
        {className: 'Exc.L4.RORB.CACNG5',               IdentifiedType: 'O/LM',             color: '#008FCC'},
        {className: 'Exc.L4.5.RORB.ASCL1',                IdentifiedType: 'O-Bi',             color: '#0070AD'},
        {className: 'Exc.L4.5.RORB.AIM2',              IdentifiedType: 'O-Bi',             color: '#0070AD'},
        {className: 'Exc.L3.LINC00507.CTXN3',                 IdentifiedType: 'O-Bi',             color: '#0070AD'},
        {className: 'Exc.L3.THEMIS.PLA2G7',                     IdentifiedType: 'PC',               color: '#00FF00'},
        {className: 'Exc.L3.5.THEMIS.ELOF1',                     IdentifiedType: 'PC',               color: '#00FF00'},
        {className: 'Exc.L2.3.LINC00507.RPL9P17',                     IdentifiedType: 'PC',               color: '#00FF00'},
        {className: 'Exc.L3.LINC00507.PSRC1',                    IdentifiedType: 'PC Other1',        color: '#73E500'},
        {className: 'Exc.L3.5.LINC00507.SLN',                    IdentifiedType: 'PC Other2',        color: '#73E500'},
        {className: 'Exc.L3.RORB.CARTPT',                  IdentifiedType: 'Radiatum retrohip', color: '#3D855A'},
        {className: 'Exc.L3.4.RORB.FOLH1B',                  IdentifiedType: 'Radiatum retrohip', color: '#3D855A'},
        {className: 'Exc.L3.4.RORB.PRSS12',                  IdentifiedType: 'Trilaminar',       color: '#1F663B'},
        {className: 'Exc.L3.4.RORB.SEMA6D',                    IdentifiedType: 'Unidentified',     color: '#A6A6A6'},
        {className: 'Exc.L3.5.RORB.HSPB3',                         IdentifiedType: 'Unidentified',     color: '#A6A6A6'},
        {className: 'Exc.L5.6.THEMIS.OR1J1',            IdentifiedType: 'Axo-axonic',       color: '#3A19BD'},
        {className: 'Exc.L6.THEMIS.EGR3',              IdentifiedType: 'Axo-axonic',       color: '#3A19BD'},
        {className: 'Exc.L5.6.THEMIS.TMEM233',            IdentifiedType: 'Axo-axonic',       color: '#3A19BD'},
        {className: 'Exc.L6.THEMIS.LINC00343',                     IdentifiedType: 'Backprojection',   color: '#3DCCFF'},
        {className: 'Exc.L3.5.RORB.CMAHP',             IdentifiedType: 'Basket',           color: '#7757FA'},
        {className: 'Exc.L3.5.RORB.CD24',              IdentifiedType: 'Basket',           color: '#7757FA'},
        {className: 'Exc.L4.5.RORB.LCN15',           IdentifiedType: 'Bistratified',     color: '#5938DB'},
        {className: 'Exc.L3.5.THEMIS.UBE2F',               IdentifiedType: 'Bistratified',     color: '#5938DB'},
        {className: 'Exc.L5.RORB.SNHG7',                    IdentifiedType: 'Cck Calb1/Slc17a8*', color: '#FF0000'},
        {className: 'Exc.L4.5.RORB.RPL31P31',                    IdentifiedType: 'Cck Cxcl14-',      color: '#FF0000'},
        {className: 'Exc.L4.5.RORB.HNRNPA1P46',                 IdentifiedType: 'Cck Cxcl14-',      color: '#FF0000'},
        {className: 'Exc.L4.5.RORB.LINC01474',                   IdentifiedType: 'Cck Cxcl14-',      color: '#FF0000'},
        {className: 'Exc.L4.6.RORB.HPCA',      IdentifiedType: 'Cck Cxcl14+',      color: '#996E00'},
        {className: 'Exc.L5.6.RORB.LINC00320',      IdentifiedType: 'Cck Cxcl14+',      color: '#996E00'},
        {className: 'Exc.L5.RORB.LINC01202',        IdentifiedType: 'Cck Cxcl14+',      color: '#996E00'},
        {className: 'Exc.L6.THEMIS.C6orf48',   IdentifiedType: 'Cck Cxcl14+',      color: '#996E00'},
        {className: 'Exc.L5.6.THEMIS.GPR21',           IdentifiedType: 'Cck Cxcl14+',      color: '#996E00'},
        {className: 'Exc.L5.6.THEMIS.THTPA',             IdentifiedType: 'Cck Vip Cxcl14-',  color: '#FF0000'},
        {className: 'Exc.L5.6.THEMIS.IL7R',         IdentifiedType: 'Cck Vip Cxcl14-',  color: '#FF0000'},
        {className: 'Exc.L6.FEZF2.VWA2',            IdentifiedType: 'Cck Vip Cxcl14-',  color: '#FF0000'},
        {className: 'Exc.L5.6.FEZF2.ANKRD20A1',               IdentifiedType: 'Cck Vip Cxcl14+',  color: '#996E00'},
        {className: 'Exc.L6.FEZF2.FAM95C',         IdentifiedType: 'CGE NGF',          color: '#FF00E6'},
        {className: 'Exc.L6.FEZF2.CPZ',            IdentifiedType: 'CGE NGF',          color: '#FF00E6'},
        {className: 'Exc.L6.FEZF2.P4HA3',          IdentifiedType: 'CGE NGF',          color: '#FF00E6'},
        {className: 'Exc.L6.FEZF2.SLITRK6',                 IdentifiedType: 'Hippocamposeptal', color: '#1FADEB'},
        {className: 'Exc.L6.FEZF2.TBCC',               IdentifiedType: 'Hippocamposeptal', color: '#1FADEB'},
        {className: 'Exc.L6.FEZF2.ETV4',               IdentifiedType: 'Hippocamposeptal', color: '#1FADEB'},
        {className: 'Exc.L6.FEZF2.TBC1D26',             IdentifiedType: 'Hippocamposeptal', color: '#1FADEB'},
        {className: 'Exc.L6.FEZF2.KRT17',        IdentifiedType: 'IS1',              color: '#BDA800'},
        {className: 'Exc.L3.5.FEZF2.ONECUT1',         IdentifiedType: 'IS1',              color: '#BDA800'},
        {className: 'Exc.L3.5.FEZF2.DCN',           IdentifiedType: 'IS1',              color: '#BDA800'},
        {className: 'Exc.L5.FEZF2.MORN2',                IdentifiedType: 'IS2',              color: '#FAE52E'},
        {className: 'Exc.L5.FEZF2.SCN7A',                 IdentifiedType: 'IS2',              color: '#FAE52E'},
        {className: 'Exc.L5.6.FEZF2.CABP7',               IdentifiedType: 'IS3',              color: '#DBC70F'},
        {className: 'Exc.L5.FEZF2.DYRK2',             IdentifiedType: 'IS3',              color: '#DBC70F'},
        {className: 'Exc.L5.6.FEZF2.MYBPHL',               IdentifiedType: 'IS3',              color: '#DBC70F'},
        {className: 'Exc.L5.6.FEZF2.CYP26B1',          IdentifiedType: 'Ivy',              color: '#994D91'},
        {className: 'Exc.L5.6.FEZF2.RSAD2',           IdentifiedType: 'MGE NGF',          color: '#994D91'},
        {className: 'Astro.L1.6.FGFR3.ETNPPL',                  IdentifiedType: 'NGF/I-S transition', color: '#FF00E6'},
        {className: 'Astro.L1.FGFR3.MT1G',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Astro.L1.FGFR3.FOS',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'OPC.L1.6.MYT1',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Oligo.L4.6.MOBP.COL18A1',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Oligo.L4.6.OPALIN',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'VLMC.L1.3.CYP1B1',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Peri.L1.6.MUSTN1',                         IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Endo.L2.5.CLDN5',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Micro.L1.6.C1QC',                      IdentifiedType: 'Non Neuron',       color: '#FFFFFF'},
        {className: 'Zero', IdentifiedType: 'Zero', color: '#000000'},

        // I added this. It is used in the donut chart, not in the section chart (that can be confusing, need to tide this up)
        {className: 'Other', IdentifiedType: 'Other', colorGroup: 'Other', color: '#C0C0C0'},



    ];

    return out
}